config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  get '/users/sign_in', to: 'users#sign_in' 
  post '/users/sign_in_action', to: 'users#sign_in_action' 
  delete '/users/sign_out', to: 'users#sign_out'
  delete '/invite/destroy', to: 'eventsusers#destroy', as: 'destroy_invite'
  get '/current_user_events', to: 'users#my_events', as: 'my_events'
  post 'events/:id/users/:id', to: 'eventsusers#create', as: 'events_users'
  resources :users
  resources :events 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: :user_id

  has_many :events_users, foreign_key: :attended_event_id
  has_many :attendees, through: :events_users, source: :attendee

  scope :past, -> { where('date < ?', Time.now) }
  scope :upcoming, -> { where('date >= ?', Time.now) }

  validates :title, length: { minimum: 10 }, presence: true, uniqueness: true
  validates :body, presence: true, length: { minimum: 20 }
  validates :place, presence: true, length: { minimum: 2 }
  validates :date, presence: true
end

app/models/events_user.rb
class EventsUser < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
  validates :attendee, uniqueness: { scope: [:attended_event] }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, dependent: :destroy

  has_many :events_users, foreign_key: :attendee_id
  has_many :attended_events, through: :events_users, source: :attended_event

  validates :username, length: { in: 3..20 }, presence: true, uniqueness: true
  validates :email, presence: true, length: { in: 10..40 }, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    @past_events = Event.past
    @upcoming_events = Event.upcoming
  end

  def show
    @attendees = Event.find(params[:id]).attendees
    out_ids = @attendees.map(&:id).push(session[:user_id])
    @users = User.where('id NOT IN (?)', out_ids)
    @invite = EventsUser.new
  end

  def new
    @event = Event.new
  end

  def create
    @event = User.find(session[:user_id]).events.build(event_params)

    if @event.save
      @invite = EventsUser.new(attendee_id: session[:user_id], attended_event_id: @event.id)

      if @invite.save
        redirect_to events_path, notice: 'A new event was created successfuly'
      else
        @event.destroy
        render :new, alert: 'Fatal error for some reason we can\'t save your event'
      end
    else
      render :new, alert: 'Fatal error, No event was created'
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :body, :date, :place)
  end
end

app/controllers/eventsusers_controller.rb
class EventsusersController < ApplicationController
  def create
    @invite = EventsUser.new(attendee_id: params[:events_user][:attendee_id], attended_event_id: params[:id])
    if @invite.save
      redirect_to events_path, notice: 'user was invited to the event successfully'
    else
      redirect_to events_path, alert: 'User was not invited to the event please try again'
    end
  end

  def destroy
    @invite = EventsUser.find_by(attendee_id: params[:attendee_id], attended_event_id: params[:event_id])
    @invite.destroy
    redirect_to events_path, notice: 'user is no more invited to the event'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, notice: 'You have successfuly signed up.'
    else
      render 'new'
    end
  end

  def my_events
    @my_past_events = User.find(session[:user_id]).attended_events.past
    @my_up_events = User.find(session[:user_id]).attended_events.upcoming
  end

  def show
    @user = User.find(params[:id])
    @attended_events = @user.attended_events.order('date asc')
    @created_events = @user.events
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
    session.delete(:user_id)
  end

  def sign_in
    @user = User.new
  end

  def sign_in_action
    @user = User.find_by(username: user_params['username'])

    if @user.nil?
      redirect_to root_path, alert: 'Wrong Username, sorry you are not allowed to enter.'
    else
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'You signed in successfully.'
    end
  end

  def sign_out
    session.delete(:user_id)
    redirect_to root_path, notice: 'You signed out, see you later man'
  end

  private

  def user_params
    params.require(:user).permit(:username, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notification_handler
    render 'notification' if flash[:notice]
  end

  def alert_handler
    render 'alert' if flash[:alert]
  end

  def session_handler
    if session[:user_id].nil?
      render 'sign_in_menu'
    else
      render 'log_out_menu'
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_error_action(field)
    render partial: 'error_handler', locals: { source: field } if @event.errors[field].any?
  end
end

app/helpers/eventsusers_helper.rb
module EventsusersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def error_action(field)
    render partial: 'error_handler', locals: { source: field } if @user.errors[field].any?
  end

  def trash_action
    render 'trash_icon' if @user.id == session[:user_id]
  end
end

app/views/application/_alert.html.erb
<div class="notification is-danger">  
  <%= alert %>
</div>

app/views/application/_log_out_menu.html.erb
<div class="navbar-start is-flex">
  Welcome: <%= User.find(session[:user_id]).username %>
  <%= link_to "All Events", events_path, class: 'is-primary button m-l' %>
  <%= link_to "My Events", my_events_path, class: 'is-primary button m-l' %>
  <%= link_to "Users", users_path, class: 'is-primary button m-l' %>
</div>
<div class="navbar-end is-flex">
  <%= link_to "Sign Out", users_sign_out_path, method: :delete, class: 'is-danger button' %>
</div>

app/views/application/_notification.html.erb
<div class="notification is-primary">  
  <%= notice %>
</div>

app/views/application/_sign_in_menu.html.erb
<div class="navbar-end is-flex">
  <%= link_to  "Sign In", users_sign_in_path, class: 'is-primary button' %>
  <%= link_to  "Sign up", new_user_path, class: 'is-primary button m-l' %>
</div>

app/views/events/_error_handler.html.erb
<% @event.errors[source].each do |msg| %>
  <p class="error"><%= msg %></p>
<% end %>

app/views/events/index.html.erb
<div class="columns">
  <div class="column is-three-fifths is-offset-one-fifth">
    <div class="box">
      <article class="media">
        <div class="media-content">
          <div class="content">
            <div class="">
                  <h1 class="has-text-white has-background-info has-text-centered"> Previous Events:</h1>
              <div class="events-container">
                
                <% @past_events.each do |event| %>
                    <div class="card">
                      <header class="card-header">
                        <p class="card-header-title has-text-centered is-block">
                         <%= event.title %>
                        </p>
                      </header>
                      <div class="card-content">
                        <div class="content">
                          <%= event.body %><br />
                          Location: <a href="#"><%= event.place %></a>
                          <br>
                          <time datetime="2016-01-01">Date: <%= event.date %></time>
                        </div>
                      </div>
                      <footer class="card-footer">
                        <%= link_to "Show", event_path(event), class:"card-footer-item" %>
                      </footer>
                    </div>
                <% end %>
              
              </div>
            </div>
            <div class="">
              <h1 class="has-text-white has-background-info has-text-centered">Upcoming Events:</h1>
              <div class="events-container">
                <% @upcoming_events.each do |event| %>
                    <div class="card">
                      <header class="card-header">
                        <p class="card-header-title has-text-centered is-block">
                         <%= event.title %>
                        </p>
                      </header>
                      <div class="card-content">
                        <div class="content">
                          <%= event.body %><br />
                          Location: <a href="#"><%= event.place %></a>
                          <br>
                          <time datetime="2016-01-01">Date: <%= event.date %></time>
                        </div>
                      </div>
                      <footer class="card-footer">
                        <%= link_to "Show", event_path(event), class:"card-footer-item" %>
                      </footer>
                    </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </article>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="columns is-centered">
  <div class="column is-one-third">
    <div class="box"> 
      <h1 class="title is-5 has-background-info has-text-centered has-text-white"> Create event  </h1>
        <%= form_for @event do |f| %>
          <div class="flex-centered">
            <%= f.label :title, class: 'tag is-large' %>
            <%= f.text_field :title, class: 'input m-ud' %>
            <%= event_error_action(:title) %>

            <%= f.label :body, class: 'tag is-large' %>
            <%= f.text_area :body, class: 'textarea m-ud' %>
            <%= event_error_action(:body) %>

            <%= f.label :place, class: 'tag is-large' %>
            <%= f.text_field :place, class: 'input m-ud' %>
            <%= event_error_action(:place) %>

            <%= f.label :date, class: 'tag is-large' %>
            <%= f.date_field :date, class: 'input m-ud' %>
            <%= event_error_action(:date) %>

            <%= f.submit "Create Event", class: 'button is-primary m-ud' %>
          </div>
        <% end %>
    </div> 
  </div> 
</div> 

app/views/events/show.html.erb
<div class="columns is-centered">
  <div class="box column is-half">
    <h1 class="title has-text-white has-text-centered has-background-info">Attendees List</h1>
    <div class="users-container-vertical">
      <% @attendees.each do |attendee| %>
        <div class="box">
          <article class="media">
            <div class="media-left">
              <figure class="image is-64x64">
                <img src="https://bulma.io/images/placeholders/128x128.png" alt="Image">
              </figure>
            </div>
            <div class="media-content">
              <div class="content">
                <p>
                  <strong class="is-5"><%= attendee.username %></strong>
                </p>
              </div>
              <nav class="level is-mobile">
                <div class="level-left">
                  <%= link_to destroy_invite_path(attendee_id: attendee.id, event_id: params[:id]), method: :delete, class: 'level-item' do %>
                    <span class="icon is-small">
                      <i class="fas fa-trash has-text-danger" aria-hidden="true"></i>
                    </span>
                  <% end %>
                </div>
              </nav>
            </div>
          </article>
        </div>
      <% end %>
      <%= form_for @invite do |f| %>
        <div class="select">
          <%= f.collection_select(:attendee_id, @users, :id, :username) %>
        </div>
        <%= f.submit "invite user", class: 'button is-info' %>
      <% end %>
    
    
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css' %>
  </head>

  <body>
    <%= notification_handler %>
    <%= alert_handler %>
    <nav class="navbar is-info">
      <div class="navbar-menu">
        <%= session_handler %>
      </div>
    </nav>
    
    <div class="my-content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_error_handler.html.erb
<% @user.errors[source].each do |msg| %>
  <p class="error"><%= msg %></p>
<% end %>

app/views/users/_trash_icon.html.erb
<%= link_to user_path, method: :delete,  class: 'level-item' do %>
  <span class="icon is-small">
    <i class="fas fa-trash has-text-danger" aria-hidden="true"></i>
  </span>
<% end %>

app/views/users/index.html.erb
<div class="is-block">
  <h1 class="title is-2"> All Users </h1>
</div>

<div class="users-container">
  <% @users.each do |user| %>
    <div class="box">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <img src="https://bulma.io/images/placeholders/128x128.png" alt="Image">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong><%= user.username %></strong>, <small><%= user.email %></small>
              <br>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            </p>
          </div>
          <nav class="level is-mobile">
            <div class="level-left">
              <%= link_to user_path(user), class: 'level-item' do %>
                <span class="icon is-small">
                  <i class="fas fa-address-card" aria-hidden="true"></i>
                </span>
              <% end %>
            </div>
          </nav>
        </div>
      </article>
    </div>
  <% end %>
</div>

app/views/users/my_events.html.erb
<div class="columns">
  <div class="column is-three-fifths is-offset-one-fifth">
    <div class="box">
      <article class="media">
        <div class="media-content">
          <div class="content">
            <div class="">
                  <h1 class="has-text-white has-background-info has-text-centered"> Previous Events:</h1>
              <div class="events-container">
                <% @my_past_events.each do |event| %>
                    <div class="card">
                      <header class="card-header">
                        <p class="card-header-title has-text-centered is-block">
                         <%= event.title %>
                        </p>
                      </header>
                      <div class="card-content">
                        <div class="content">
                          <%= event.body %>
                          <br />
                          Location: <a href="#"><%= event.place %></a>
                          <br>
                          <time datetime="2016-01-01">Date: <%= event.date %></time>
                        </div>
                      </div>
                      <footer class="card-footer">
                        <%= link_to "Show", event_path(event), class:"card-footer-item" %>
                      </footer>
                    </div>
                <% end %>
              
              </div>
            </div>
            <div class="">
              <h1 class="has-text-white has-background-info has-text-centered">Upcoming Events:</h1>
              <div class="events-container">
                <% @my_up_events.each do |event| %>
                    <div class="card">
                      <header class="card-header">
                        <p class="card-header-title has-text-centered is-block">
                         <%= event.title %>
                        </p>
                      </header>
                      <div class="card-content">
                        <div class="content">
                          <%= event.body %>
                          <br />
                          Location: <a href="#"><%= event.place %></a>
                          <br>
                          <time datetime="2016-01-01">Date: <%= event.date %></time>
                        </div>
                      </div>
                      <footer class="card-footer">
                        <%= link_to "Show", event_path(event), class:"card-footer-item" %>
                      </footer>
                    </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </article>
    </div>

    <div class="has-text-centered is-block">
      <%= link_to  "Create a new event", new_event_path, class: 'button is-success' %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="columns is-centered">
  <div class="column is-one-third">
    <div class="box"> 
      <h1 class="title is-5 has-background-info has-text-centered has-text-white"> Sign Up </h1>
        <%= form_for @user, url: users_path do |f| %>
          <div class="flex-centered">
            <%= f.label :username, class: 'tag is-large' %>
            <%= f.text_field :username, class: 'input m-ud' %>
            <%= error_action(:username) %>

            <%= f.label :email, class: 'tag is-large' %>
            <%= f.text_field :email, class: 'input m-ud' %>
            <%= error_action(:email) %>

            <%= f.submit "Sign up", class: 'button is-primary m-ud' %>
          </div>
        <% end %>
    </div> 
  </div> 
</div> 

app/views/users/show.html.erb
<div class="columns is-centered">
  <div class="column is-one-third">
    <div class="box user-card">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <img src="https://bulma.io/images/placeholders/128x128.png" alt="Image">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong><%= @user.username %></strong>, <small><%= @user.email %></small>
              <br>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            </p>
          </div>
          <nav class="level is-mobile">
            <div class="level-left">
              <%= trash_action %>
            </div>
          </nav>
        </div>
      </article>
    </div>
  </div>
</div>
<div class="columns">
  <div class="column is-three-fifths is-offset-one-fifth ">
    <div class="box">
      <article class="media">
        <div class="media-content">
          <div class="content">
            <h1 class="">Created Events</h1>
            <div class="columns">
              <div class="column">
                    <h1 class="has-text-white has-background-info has-text-centered"> Previous Events:</h1>
                <div class="events-container">
                  
                  <% @created_events.filter{ |event| event.date < Time.now }.each do |event| %>
                      <div class="card">
                        <header class="card-header">
                          <p class="card-header-title has-text-centered is-block">
                          <%= event.title %>
                          </p>
                        </header>
                        <div class="card-content">
                          <div class="content">
                            <%= event.body %><br />
                            Location: <a href="#"><%= event.place %></a>
                            <br>
                            <time datetime="2016-01-01">Date: <%= event.date %></time>
                          </div>
                        </div>
                        <footer class="card-footer">
                          <%= link_to "Show", event_path(event), class:"card-footer-item" %>
                        </footer>
                      </div>
                  <% end %>
                
                </div>
              </div>
            
              <div class="column">
                <h1 class="has-text-white has-background-info has-text-centered">Upcoming Events:</h1>
                <div class="events-container">
                  <%  @created_events.filter{ |event| event.date >= Time.now }.each do |event| %>
                      <div class="card">
                        <header class="card-header">
                          <p class="card-header-title has-text-centered is-block">
                          <%= event.title %>
                          </p>
                        </header>
                        <div class="card-content">
                          <div class="content">
                            <%= event.body %><br />
                            Location: <a href="#"><%= event.place %></a>
                            <br>
                            <time datetime="2016-01-01">Date: <%= event.date %></time>
                          </div>
                        </div>
                        <footer class="card-footer">
                          <%= link_to "Show", event_path(event), class:"card-footer-item" %>
                        </footer>
                      </div>
                  <% end %>
                </div>
            </div>
            </div>
          </div>
        </div>
      </article>
    </div>



    <div class="box">
      <article class="media">
        <div class="media-content">
          <div class="content">
            <h1 class="">Attended Events</h1>
            <div class="columns">
              <div class="column">
                    <h1 class="has-text-white has-background-info has-text-centered"> Previous Events:</h1>
                <div class="events-container">
                  
                  <% @attended_events.filter{ |event| event.date < Time.now }.each do |event| %>
                      <div class="card">
                        <header class="card-header">
                          <p class="card-header-title has-text-centered is-block">
                          <%= event.title %>
                          </p>
                        </header>
                        <div class="card-content">
                          <div class="content">
                            <%= event.body %><br />
                            Location: <a href="#"><%= event.place %></a>
                            <br>
                            <time datetime="2016-01-01">Date: <%= event.date %></time>
                          </div>
                        </div>
                        <footer class="card-footer">
                          <%= link_to "Show", event_path(event), class:"card-footer-item" %>
                        </footer>
                      </div>
                  <% end %>
                
                </div>
              </div>
            
              <div class="column">
                <h1 class="has-text-white has-background-info has-text-centered">Upcoming Events:</h1>
                <div class="events-container">
                  <%  @attended_events.filter{ |event| event.date >= Time.now }.each do |event| %>
                      <div class="card">
                        <header class="card-header">
                          <p class="card-header-title has-text-centered is-block">
                          <%= event.title %>
                          </p>
                        </header>
                        <div class="card-content">
                          <div class="content">
                            <%= event.body %><br />
                            Location: <a href="#"><%= event.place %></a>
                            <br>
                            <time datetime="2016-01-01">Date: <%= event.date %></time>
                          </div>
                        </div>
                        <footer class="card-footer">
                          <%= link_to "Show", event_path(event), class:"card-footer-item" %>
                        </footer>
                      </div>
                  <% end %>
                </div>
            </div>
            </div>
          </div>
        </div>
      </article>
    </div>

    <div class="has-text-centered is-block">
      <%= link_to  "Create a new event", new_event_path, class: 'button is-success' %>
    </div>
  </div>
</div>

app/views/users/sign_in.html.erb
<div class="columns is-centered">
  <div class="column is-one-third">
    <div class="box"> 
      <h1 class="title is-5 has-background-info has-text-centered has-text-white"> Log In </h1>
        <%= form_for @user, url: users_sign_in_action_path do |f| %>
          <div class="flex-centered">
            <%= f.label :username, class: 'tag is-large' %>
            <%= f.text_field :username, class: 'input m-ud' %>
            <%= f.submit "Log in", class: 'button is-primary m-ud' %>
          </div>
        <% end %>
    </div> 
  </div> 
</div> 